insert into Education values (1, 'начальное');
insert into Education values (2, 'среднее');
insert into Education values (3, 'средне-специальное');
insert into Education values (4, 'высшее');

insert into Posts values ('Администратор', 70360.87);
insert into Posts values ('Консультант-кассир', 62520.09);
insert into Posts values ('Грузчик', 56789.80);
insert into Posts values ('Уборщик', 51250.76);

insert into Colors values (0, 'разноцветный');
insert into Colors values (1, 'красный');
insert into Colors values (2, 'синий');
insert into Colors values (3, 'зеленый');
insert into Colors values (4, 'желтый');
insert into Colors values (5, 'оранжевый');
insert into Colors values (6, 'фиолетовый');
insert into Colors values (7, 'розовый');
insert into Colors values (8, 'черный');
insert into Colors values (9, 'белый');
insert into Colors values (10, 'серый');
insert into Colors values (11, 'коричневый');
insert into Colors values (12, 'голубой');
insert into Colors values (13, 'кремовый');

insert into Categories values (1, 'футболки');
insert into Categories values (2, 'джинсы');
insert into Categories values (3, 'платья');
insert into Categories values (4, 'юбки');
insert into Categories values (5, 'рубашки');
insert into Categories values (6, 'куртки');
insert into Categories values (7, 'брюки');
insert into Categories values (8, 'пиджаки');
insert into Categories values (9, 'пальто');
insert into Categories values (10, 'шорты');
insert into Categories values (11, 'туфли');
insert into Categories values (12, 'ботинки');
insert into Categories values (13, 'кроссовки');
insert into Categories values (14, 'сандалии');
insert into Categories values (15, 'сапоги');

insert into Materials values (1, 'хлопок');
insert into Materials values (2, 'акрил');
insert into Materials values (3, 'шерсть');
insert into Materials values (4, 'кожа');
insert into Materials values (5, 'полиэстер');
insert into Materials values (6, 'нейлон');
insert into Materials values (7, 'шелк');
insert into Materials values (8, 'лен');
insert into Materials values (9, 'вельвет');
insert into Materials values (10, 'твид');
insert into Materials values (11, 'деним');
insert into Materials values (12, 'велюр');
insert into Materials values (13, 'спандекс');
insert into Materials values (14, 'кашемир');
insert into Materials values (15, 'шифон');
insert into Materials values (16, 'полиуретан');
insert into Materials values (17, 'эластан');
insert into Materials values (18, 'акрил');
insert into Materials values (19, 'замша');

insert into Brands values (1, 'Nike');
insert into Brands values (2, 'Adidas');
insert into Brands values (3, 'Zara');
insert into Brands values (4, 'H&M');
insert into Brands values (5, 'Gucci');
insert into Brands values (6, 'Levis');
insert into Brands values (7, 'Prada');
insert into Brands values (8, 'Balenciaga');
insert into Brands values (9, 'Versace');
insert into Brands values (10, 'Calvin Klein');
insert into Brands values (11, 'Puma');
insert into Brands values (12, 'Converse');
insert into Brands values (13, 'New Balance');
insert into Brands values (14, 'Louis Vuitton');
insert into Brands values (15, 'Fendi');
insert into Brands values (16, 'Under Armour');
insert into Brands values (17, 'Tommy Hilfiger');
insert into Brands values (18, 'Ralph Lauren');
insert into Brands values (19, 'Chanel');
insert into Brands values (20, 'Burberry');
